title: Page
icon: file-text-o

fields:
    navigationHeadline:
        label: Navigation
        type: headline
        numbered: false

    menuTitle:
        label: Menu Title
        type: text
        width: 3/4

    isMenuItem:
        width: 1/4
        label: Navigation
        type: checkbox
        text: Is Menu Item


    generalHeadline:
        label: General Settings
        type: headline
        numbered: false

    title:
        label: Page Title
        type:  title

    text:
        label: Text
        type:  textarea
