title: Page

fields:
  title:
    label: Page Title
    type:  text

  menuTitle:
    label: Menu Title
    type: title
    required: true
    width: 3/4

  isMenuItem:
    width: 1/4
    label: Navigation
    type: checkbox
    text: Is Menu Item

  text:
    label: Text
    type:  textarea
