title: Website Globals

fields:
  generalHeadline:
    label:
        de: Allgemeine Einstellungen
        en: General Settings
    type: headline
    numbered: false

  title:
    label: Website name
    type: title
    width: 1/2

  slogan:
    label: Slogan
    type: text
    width: 1/2

  copyright:
    label: Copyright
    type:  textarea

  socialHeadline:
    label: Social Media Settings
    type: headline
    numbered: false

  twitter:
    label: Twitter Handle (just its name)
    type: text
    width: 1/2

  supportemail:
    label: Support Email Address
    type: text
    width: 1/2

  appstoreHeadline:
    label: Mac & iOS App Store Settings
    type: headline
    numbered: false

  iosAppstore_label:
    label: iOS App Store Button Label
    type: text
    width: 1/2

  iosAppstore:
    label: iOS App Store URL
    type: text
    width: 1/2

  macAppstore_label:
    label: macOS App Store Button Label
    type: text
    width: 1/2

  macAppstore:
    label: macOS App Store URL
    type: text
    width: 1/2

  headerImagesHeadline:
    label: Header Images
    type: headline
    numbered: false

  headerImage1x:
    label: Website Header Image (@1x)
    type: image
    width: 1/2

  headerImage2x:
    label: Website Header Image (@2x)
    type: image
    width: 1/2

  headerBlogImage1x:
    label: Blog Header Image (@1x)
    type: image
    width: 1/2

  headerBlogImage2x:
    label: Blog Header Image (@2x)
    type: image
    width: 1/2

  header404Image1x:
    label: 404-Error Header Image (@1x)
    type: image
    width: 1/2

  header404Image2x:
    label: 404-Error Header Image (@2x)
    type: image
    width: 1/2
