# Site settings
title: stefantrauth.de
email: 
url: https://stefantrauth.de
description: "Coder, Blogger, Podcaster"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#222222'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/funkenstrahlen
  - title: github
    url: https://github.com/funkenstrahlen

# Build settings
markdown: kramdown
permalink: pretty
